# Generated by Django 4.1.11 on 2023-10-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeexperience_employeeeducation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeexperience',
            name='company1name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company2name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company3name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='coursehsc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
